### ISSUE TITLE
Enhance README

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/ODataApi#18]
Please put all the useful information from https://github.com/StarcounterApps/ODataApi/issues/14#issue-236554506 to README.md

Specifically:

- current featureset
   - link to the roadmap (https://github.com/StarcounterApps/ODataApi/issues/14). Perhaps please rename this issue to "Roadmap"?
- using the app
- tools
- related links

**Comment by warpech** [comment]
Also, add the info from: https://github.com/StarcounterApps/ODataApi/issues/17#issuecomment-312290222

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterApps/ODataApi/pull/22

**Comment by un-tone** [comment]
Closing as done
