### ISSUE TITLE
run.bat cannot find the executable

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/ODataApi#21]
After calling `build.bat`, then `run.bat` I get the following error:

```txt
c:\www\ODataApi>run.bat

ScErrExecutableNotFound (SCERR10019): The executable file cound not be found. File: "c:\www\ODataApi\src\ODataApi\bin\Debug\ODataApi.exe"
Version: 2.3.1.6682.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10019.

Type "star -h" or "staradmin -h" to see help
```

**Comment by warpech** [comment]
This is the output of `build.bat`:

Seems that the problem is this:

> The project "ODataApi" is not selected for building in solution configuration "Debug|Any CPU".

<details>
<pre>
c:\www\ODataApi>build.bat
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26430.14
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework\v4.0.30319'.
All packages listed in packages.config are already installed.
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 7/4/2017 7:17:20 PM.
Project "c:\www\ODataApi\ODataApi.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
ValidateProjects:
  The project "ODataApi" is not selected for building in solution configuration "Debug|Any CPU".
  The project "ODataApi_AcceptanceHelper" is not selected for building in solution configuration "Debug|Any CPU".
Project "c:\www\ODataApi\ODataApi.sln" (1) is building "c:\www\ODataApi\test\ODataApi.Tests\ODataApi.Tests.csproj" (2)
on node 1 (default targets).
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the i
nput files.
CoreCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin\Roslyn\csc.exe /noconfig /nowarn:17
  01,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE /highentropyva+ /reference:"C:\Program Files (x86)
  \Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll" /reference:c:\www\ODataApi\package
  s\Microsoft.OData.Core.6.15.0\lib\portable-net45+win+wpa81\Microsoft.OData.Core.dll /reference:c:\www\ODataApi\packag
  es\Microsoft.OData.Edm.6.15.0\lib\portable-net45+win+wpa81\Microsoft.OData.Edm.dll /reference:c:\www\ODataApi\package
  s\Microsoft.Spatial.6.15.0\lib\portable-net45+win+wpa81\Microsoft.Spatial.dll /reference:c:\www\ODataApi\packages\Mic
  rosoft.Bcl.Async.1.0.168\lib\net40\Microsoft.Threading.Tasks.dll /reference:c:\www\ODataApi\packages\Microsoft.Bcl.As
  ync.1.0.168\lib\net40\Microsoft.Threading.Tasks.Extensions.Desktop.dll /reference:c:\www\ODataApi\packages\Microsoft.
  Bcl.Async.1.0.168\lib\net40\Microsoft.Threading.Tasks.Extensions.dll /reference:"C:\Program Files (x86)\Reference Ass
  emblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" /reference:c:\www\ODataApi\packages\NUnit.3.7.0\lib\net4
  5\nunit.framework.dll /reference:c:\www\ODataApi\packages\Simple.OData.V4.Client.4.26.0\lib\portable-net45+win8+wp8+w
  pa81\Simple.OData.Client.Core.dll /reference:c:\www\ODataApi\packages\Simple.OData.V4.Client.4.26.0\lib\portable-net4
  5+win8+wp8+wpa81\Simple.OData.Client.Dynamic.dll /reference:c:\www\ODataApi\packages\Simple.OData.V4.Client.4.26.0\li
  b\portable-net45+win8+wp8+wpa81\Simple.OData.Client.V4.Adapter.dll /reference:"C:\Program Files (x86)\Reference Assem
  blies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies
  \Microsoft\Framework\.NETFramework\v4.5\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Referen
  ce Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.dll" /reference:"C:\Program Files (x86)\Reference As
  semblies\Microsoft\Framework\.NETFramework\v4.5\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\M
  icrosoft\Framework\.NETFramework\v4.5\System.Net.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microso
  ft\Framework\.NETFramework\v4.5\System.Net.Http.dll" /reference:c:\www\ODataApi\packages\Microsoft.Net.Http.2.2.28\li
  b\net45\System.Net.Http.Extensions.dll /reference:c:\www\ODataApi\packages\Microsoft.Net.Http.2.2.28\lib\net45\System
  .Net.Http.Primitives.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4
  .5\System.Net.Http.WebRequest.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFr
  amework\v4.5\System.Web.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramewor
  k\v4.5\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5
  \System.Xml.Linq.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\
  Facades\System.Collections.Concurrent.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framewor
  k\.NETFramework\v4.5\Facades\System.Collections.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsof
  t\Framework\.NETFramework\v4.5\Facades\System.ComponentModel.Annotations.dll" /reference:"C:\Program Files (x86)\Refe
  rence Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ComponentModel.dll" /reference:"C:\Program Fil
  es (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ComponentModel.EventBasedAsync.dl
  l" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Diag
  nostics.Contracts.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5
  \Facades\System.Diagnostics.Debug.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.N
  ETFramework\v4.5\Facades\System.Diagnostics.Tools.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Micros
  oft\Framework\.NETFramework\v4.5\Facades\System.Diagnostics.Tracing.dll" /reference:"C:\Program Files (x86)\Reference
   Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Dynamic.Runtime.dll" /reference:"C:\Program Files (
  x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Globalization.dll" /reference:"C:\Pro
  gram Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.IO.dll" /reference:"C:\Pr
  ogram Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Linq.dll" /reference:"C:
  \Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Linq.Expressions.dll"
   /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Linq.P
  arallel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\S
  ystem.Linq.Queryable.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v
  4.5\Facades\System.Net.NetworkInformation.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram
  ework\.NETFramework\v4.5\Facades\System.Net.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\M
  icrosoft\Framework\.NETFramework\v4.5\Facades\System.Net.Requests.dll" /reference:"C:\Program Files (x86)\Reference A
  ssemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ObjectModel.dll" /reference:"C:\Program Files (x86)\R
  eference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Reflection.dll" /reference:"C:\Program File
  s (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Reflection.Emit.dll" /reference:"C
  :\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Reflection.Emit.ILGe
  neration.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\
  System.Reflection.Emit.Lightweight.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.
  NETFramework\v4.5\Facades\System.Reflection.Extensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\M
  icrosoft\Framework\.NETFramework\v4.5\Facades\System.Reflection.Primitives.dll" /reference:"C:\Program Files (x86)\Re
  ference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Resources.ResourceManager.dll" /reference:"C
  :\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.dll" /refere
  nce:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.Extens
  ions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\Syst
  em.Runtime.InteropServices.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFrame
  work\v4.5\Facades\System.Runtime.InteropServices.WindowsRuntime.dll" /reference:"C:\Program Files (x86)\Reference Ass
  emblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.Numerics.dll" /reference:"C:\Program Files (x86
  )\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.Serialization.Json.dll" /referen
  ce:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.Seriali
  zation.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5
  \Facades\System.Runtime.Serialization.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram
  ework\.NETFramework\v4.5\Facades\System.Security.Principal.dll" /reference:"C:\Program Files (x86)\Reference Assembli
  es\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ServiceModel.Duplex.dll" /reference:"C:\Program Files (x86)\
  Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ServiceModel.Http.dll" /reference:"C:\Prog
  ram Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ServiceModel.NetTcp.dll" /
  reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ServiceM
  odel.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\F
  acades\System.ServiceModel.Security.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\
  .NETFramework\v4.5\Facades\System.Text.Encoding.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsof
  t\Framework\.NETFramework\v4.5\Facades\System.Text.Encoding.Extensions.dll" /reference:"C:\Program Files (x86)\Refere
  nce Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Text.RegularExpressions.dll" /reference:"C:\Prog
  ram Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Threading.dll" /reference:
  "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Threading.Tasks.dl
  l" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Thre
  ading.Tasks.Parallel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v
  4.5\Facades\System.Xml.ReaderWriter.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\
  .NETFramework\v4.5\Facades\System.Xml.XDocument.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsof
  t\Framework\.NETFramework\v4.5\Facades\System.Xml.XmlSerializer.dll" /debug+ /debug:full /filealign:512 /optimize- /o
  ut:obj\Debug\ODataApi.Tests.dll /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Team Tools
  \Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" /subsystemversion:6.00 /target:library /utf8output
   Tests\BaseTest.cs Tests\ModifyDataTests.cs Properties\AssemblyInfo.cs Utilities\Config.cs "C:\Users\warpe\AppData\Lo
  cal\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cs"
  Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\Profession
  al\MSBuild\15.0\bin\Roslyn
_CopyFilesMarkedCopyLocal:
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Core.6.15.0\lib\portable-net45+win+wpa81\Microsoft.OData.
  Core.dll" to "bin\Debug\Microsoft.OData.Core.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Edm.6.15.0\lib\portable-net45+win+wpa81\Microsoft.OData.E
  dm.dll" to "bin\Debug\Microsoft.OData.Edm.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Spatial.6.15.0\lib\portable-net45+win+wpa81\Microsoft.Spatial.d
  ll" to "bin\Debug\Microsoft.Spatial.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Bcl.Async.1.0.168\lib\net40\Microsoft.Threading.Tasks.dll" to "
  bin\Debug\Microsoft.Threading.Tasks.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Bcl.Async.1.0.168\lib\net40\Microsoft.Threading.Tasks.Extension
  s.Desktop.dll" to "bin\Debug\Microsoft.Threading.Tasks.Extensions.Desktop.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Bcl.Async.1.0.168\lib\net40\Microsoft.Threading.Tasks.Extension
  s.dll" to "bin\Debug\Microsoft.Threading.Tasks.Extensions.dll".
  Copying file from "c:\www\ODataApi\packages\NUnit.3.7.0\lib\net45\nunit.framework.dll" to "bin\Debug\nunit.framework.
  dll".
  Copying file from "c:\www\ODataApi\packages\Simple.OData.V4.Client.4.26.0\lib\portable-net45+win8+wp8+wpa81\Simple.OD
  ata.Client.Core.dll" to "bin\Debug\Simple.OData.Client.Core.dll".
  Copying file from "c:\www\ODataApi\packages\Simple.OData.V4.Client.4.26.0\lib\portable-net45+win8+wp8+wpa81\Simple.OD
  ata.Client.Dynamic.dll" to "bin\Debug\Simple.OData.Client.Dynamic.dll".
  Copying file from "c:\www\ODataApi\packages\Simple.OData.V4.Client.4.26.0\lib\portable-net45+win8+wp8+wpa81\Simple.OD
  ata.Client.V4.Adapter.dll" to "bin\Debug\Simple.OData.Client.V4.Adapter.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Net.Http.2.2.28\lib\net45\System.Net.Http.Extensions.dll" to "b
  in\Debug\System.Net.Http.Extensions.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Net.Http.2.2.28\lib\net45\System.Net.Http.Primitives.dll" to "b
  in\Debug\System.Net.Http.Primitives.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Core.6.15.0\lib\portable-net45+win+wpa81\Microsoft.OData.
  Core.xml" to "bin\Debug\Microsoft.OData.Core.xml".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Edm.6.15.0\lib\portable-net45+win+wpa81\Microsoft.OData.E
  dm.xml" to "bin\Debug\Microsoft.OData.Edm.xml".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Spatial.6.15.0\lib\portable-net45+win+wpa81\Microsoft.Spatial.x
  ml" to "bin\Debug\Microsoft.Spatial.xml".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Bcl.Async.1.0.168\lib\net40\Microsoft.Threading.Tasks.xml" to "
  bin\Debug\Microsoft.Threading.Tasks.xml".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Bcl.Async.1.0.168\lib\net40\Microsoft.Threading.Tasks.Extension
  s.xml" to "bin\Debug\Microsoft.Threading.Tasks.Extensions.xml".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Bcl.Async.1.0.168\lib\net40\Microsoft.Threading.Tasks.Extension
  s.Desktop.xml" to "bin\Debug\Microsoft.Threading.Tasks.Extensions.Desktop.xml".
  Copying file from "c:\www\ODataApi\packages\NUnit.3.7.0\lib\net45\nunit.framework.xml" to "bin\Debug\nunit.framework.
  xml".
  Copying file from "c:\www\ODataApi\packages\Simple.OData.V4.Client.4.26.0\lib\portable-net45+win8+wp8+wpa81\Simple.OD
  ata.Client.Core.xml" to "bin\Debug\Simple.OData.Client.Core.xml".
  Copying file from "c:\www\ODataApi\packages\Simple.OData.V4.Client.4.26.0\lib\portable-net45+win8+wp8+wpa81\Simple.OD
  ata.Client.Dynamic.xml" to "bin\Debug\Simple.OData.Client.Dynamic.xml".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Net.Http.2.2.28\lib\net45\System.Net.Http.Extensions.xml" to "b
  in\Debug\System.Net.Http.Extensions.xml".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Net.Http.2.2.28\lib\net45\System.Net.Http.Primitives.xml" to "b
  in\Debug\System.Net.Http.Primitives.xml".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Core.6.15.0\lib\portable-net45+win+wpa81\de\Microsoft.ODa
  ta.Core.resources.dll" to "bin\Debug\de\Microsoft.OData.Core.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Core.6.15.0\lib\portable-net45+win+wpa81\es\Microsoft.ODa
  ta.Core.resources.dll" to "bin\Debug\es\Microsoft.OData.Core.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Core.6.15.0\lib\portable-net45+win+wpa81\fr\Microsoft.ODa
  ta.Core.resources.dll" to "bin\Debug\fr\Microsoft.OData.Core.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Core.6.15.0\lib\portable-net45+win+wpa81\it\Microsoft.ODa
  ta.Core.resources.dll" to "bin\Debug\it\Microsoft.OData.Core.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Core.6.15.0\lib\portable-net45+win+wpa81\ja\Microsoft.ODa
  ta.Core.resources.dll" to "bin\Debug\ja\Microsoft.OData.Core.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Core.6.15.0\lib\portable-net45+win+wpa81\ko\Microsoft.ODa
  ta.Core.resources.dll" to "bin\Debug\ko\Microsoft.OData.Core.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Core.6.15.0\lib\portable-net45+win+wpa81\ru\Microsoft.ODa
  ta.Core.resources.dll" to "bin\Debug\ru\Microsoft.OData.Core.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Core.6.15.0\lib\portable-net45+win+wpa81\zh-Hans\Microsof
  t.OData.Core.resources.dll" to "bin\Debug\zh-Hans\Microsoft.OData.Core.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Core.6.15.0\lib\portable-net45+win+wpa81\zh-Hant\Microsof
  t.OData.Core.resources.dll" to "bin\Debug\zh-Hant\Microsoft.OData.Core.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Edm.6.15.0\lib\portable-net45+win+wpa81\de\Microsoft.ODat
  a.Edm.resources.dll" to "bin\Debug\de\Microsoft.OData.Edm.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Edm.6.15.0\lib\portable-net45+win+wpa81\es\Microsoft.ODat
  a.Edm.resources.dll" to "bin\Debug\es\Microsoft.OData.Edm.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Edm.6.15.0\lib\portable-net45+win+wpa81\fr\Microsoft.ODat
  a.Edm.resources.dll" to "bin\Debug\fr\Microsoft.OData.Edm.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Edm.6.15.0\lib\portable-net45+win+wpa81\it\Microsoft.ODat
  a.Edm.resources.dll" to "bin\Debug\it\Microsoft.OData.Edm.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Edm.6.15.0\lib\portable-net45+win+wpa81\ja\Microsoft.ODat
  a.Edm.resources.dll" to "bin\Debug\ja\Microsoft.OData.Edm.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Edm.6.15.0\lib\portable-net45+win+wpa81\ko\Microsoft.ODat
  a.Edm.resources.dll" to "bin\Debug\ko\Microsoft.OData.Edm.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Edm.6.15.0\lib\portable-net45+win+wpa81\ru\Microsoft.ODat
  a.Edm.resources.dll" to "bin\Debug\ru\Microsoft.OData.Edm.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Edm.6.15.0\lib\portable-net45+win+wpa81\zh-Hans\Microsoft
  .OData.Edm.resources.dll" to "bin\Debug\zh-Hans\Microsoft.OData.Edm.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.OData.Edm.6.15.0\lib\portable-net45+win+wpa81\zh-Hant\Microsoft
  .OData.Edm.resources.dll" to "bin\Debug\zh-Hant\Microsoft.OData.Edm.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Spatial.6.15.0\lib\portable-net45+win+wpa81\de\Microsoft.Spatia
  l.resources.dll" to "bin\Debug\de\Microsoft.Spatial.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Spatial.6.15.0\lib\portable-net45+win+wpa81\es\Microsoft.Spatia
  l.resources.dll" to "bin\Debug\es\Microsoft.Spatial.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Spatial.6.15.0\lib\portable-net45+win+wpa81\fr\Microsoft.Spatia
  l.resources.dll" to "bin\Debug\fr\Microsoft.Spatial.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Spatial.6.15.0\lib\portable-net45+win+wpa81\it\Microsoft.Spatia
  l.resources.dll" to "bin\Debug\it\Microsoft.Spatial.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Spatial.6.15.0\lib\portable-net45+win+wpa81\ja\Microsoft.Spatia
  l.resources.dll" to "bin\Debug\ja\Microsoft.Spatial.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Spatial.6.15.0\lib\portable-net45+win+wpa81\ko\Microsoft.Spatia
  l.resources.dll" to "bin\Debug\ko\Microsoft.Spatial.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Spatial.6.15.0\lib\portable-net45+win+wpa81\ru\Microsoft.Spatia
  l.resources.dll" to "bin\Debug\ru\Microsoft.Spatial.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Spatial.6.15.0\lib\portable-net45+win+wpa81\zh-Hans\Microsoft.S
  patial.resources.dll" to "bin\Debug\zh-Hans\Microsoft.Spatial.resources.dll".
  Copying file from "c:\www\ODataApi\packages\Microsoft.Spatial.6.15.0\lib\portable-net45+win+wpa81\zh-Hant\Microsoft.S
  patial.resources.dll" to "bin\Debug\zh-Hant\Microsoft.Spatial.resources.dll".
_CopyAppConfigFile:
  Copying file from "obj\Debug\ODataApi.Tests.csproj.App.config" to "bin\Debug\ODataApi.Tests.dll.config".
CopyFilesToOutputDirectory:
  Copying file from "obj\Debug\ODataApi.Tests.dll" to "bin\Debug\ODataApi.Tests.dll".
  ODataApi.Tests -> c:\www\ODataApi\test\ODataApi.Tests\bin\Debug\ODataApi.Tests.dll
  Copying file from "obj\Debug\ODataApi.Tests.pdb" to "bin\Debug\ODataApi.Tests.pdb".
Done Building Project "c:\www\ODataApi\test\ODataApi.Tests\ODataApi.Tests.csproj" (default targets).

Done Building Project "c:\www\ODataApi\ODataApi.sln" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.79

c:\www\ODataApi>
</pre>
</details>

**Comment by warpech** [comment]
Building with VS2017 succeeds

**Comment by warpech** [comment]
Only after changing target platform from x64 to "Any CPU" in VS2017, build succeeds. 

Why is it so? Is it because I am on a VM?

**Comment by un-tone** [comment]
FIxed in https://github.com/StarcounterApps/ODataApi/commit/42982a622227878183848932527433af09bcf113.
Closing
