### ISSUE TITLE
Make a blog post about us having this app

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/ODataApi#24]
@un-tone could you pls draft such blog post? @Mackiovello can help to pimp it up before publishing.

**Comment by un-tone** [comment]
I'm not good in writing articles :-). But I tried to do something [here](https://gist.github.com/un-tone/0070e68b3a269d2bbb3138dce16ceb18). @Mackiovello I'd appreciate any help with what I should change or add there else.

**Comment by Mackiovello** [comment]
Looks good! I made some changes to have a more positive tone:

> To access Starcounter databases outside their environments, we've created the ODataApi app. It lets you interact with Starcounter databases with the [OData protocol](http://www.odata.org/).

> The ODataApi app supports the OData V4 protocol. We have tested that it works well with Power BI Desktop and Microsoft Excel. Some previous OData versions are not compatible with V4, so check which version your data client uses before trying to use the app.

> To download and get instructions on how to use the app, go to the [GitHub repository](https://github.com/StarcounterApps/ODataApi). There, you can also post issues and create Pull Requests. 

> For instructions on how to use Power BI, there's a tutorial in the [repository wiki](https://github.com/StarcounterApps/ODataApi/wiki/How-to-use-Power-BI).

> The app works with Starcounter versions above 2.3.1.6841.

> This is a large step since it's the first time you can interact with a Starcounter database from outside a Starcounter environment. This opens a lot of doors for how Starcounter can be used. We look forward to seeing what you build together with the ODataApi app. 

Is that accurate? If it's good, I'll go ahead and publish it.

**Comment by un-tone** [comment]
Yes, looks very good!

**Comment by Mackiovello** [comment]
Great! It's published here: https://starcounter.io/announcing-odata-feed-provider-app/

Closing.
