### ISSUE TITLE
Release version 1.0

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/ODataApi#25]
@un-tone in your opinion is there anything particular needed before releasing 1.0?

**Comment by un-tone** [comment]
I think we are ready to release 1.0

**Comment by warpech** [comment]
@un-tone can you then please release the version to get close this issue?

https://github.com/Starcounter/Guidelines/blob/master/releasing-to-warehouse.md

**Comment by warpech** [comment]
This app is owned by the Apps Team but I think @LarsTjernstrom will appreciate us handing over a finished project.

**Comment by un-tone** [comment]
Done. Closing...

**Comment by warpech** [comment]
@un-tone, can you please put the version 1.0.0 to the App Warehouse?

**Comment by un-tone** [comment]
But it is already there <http://warehouse.starcounter.com/warehouse/organizations/starcounter/softwares/odataapi>

**Comment by un-tone** [comment]
I see it is available in App Warehouse:
![image](https://user-images.githubusercontent.com/1625378/34640263-6acd7976-f300-11e7-88c8-2feed2d1300b.png)

So I can close this issue.

**Comment by warpech** [comment]
Thanks for updating. It was some visibility problem, most probably it was initially not added to a Store in the Warehouse.
